package InterfaceCreator.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditorComponent;
import jetbrains.mps.openapi.editor.descriptor.SubstituteMenu;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Action_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new ActionEnum_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new ActionReference_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new Calculator_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new Input_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }
  private Collection<ConceptEditorComponent> getDeclaredEC_0(String editorComponentId) {
    if ("InterfaceCreator.editor.ActionEnums".equals(editorComponentId)) {
      return Collections.singletonList(new ActionEnums());
    }
    return Collections.emptyList();
  }
  @NotNull
  public Collection<ConceptEditorComponent> getDeclaredEditorComponents(SAbstractConcept concept, String editorComponentId) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex1.index(cncpt)) {
      case 0:
        return getDeclaredEC_0(editorComponentId);
      default:
    }
    return Collections.emptyList();
  }


  @NotNull
  @Override
  public Collection<SubstituteMenu> getDeclaredDefaultSubstituteMenus(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex2.index(cncpt)) {
      case 0:
        return Collections.<SubstituteMenu>singletonList(new ActionReference_SubstituteMenu());
      default:
    }
    return Collections.<SubstituteMenu>emptyList();
  }

  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xf4edb82064c444beL, 0x93d796440bb7833cL, 0x4876abac40debcL), MetaIdFactory.conceptId(0xf4edb82064c444beL, 0x93d796440bb7833cL, 0x393d35efb0d226f9L), MetaIdFactory.conceptId(0xf4edb82064c444beL, 0x93d796440bb7833cL, 0x393d35efb0d2d20aL), MetaIdFactory.conceptId(0xf4edb82064c444beL, 0x93d796440bb7833cL, 0x4876abac3d2f70L), MetaIdFactory.conceptId(0xf4edb82064c444beL, 0x93d796440bb7833cL, 0x4876abac40debbL)).seal();
  private static final ConceptSwitchIndex conceptIndex1 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xf4edb82064c444beL, 0x93d796440bb7833cL, 0x4876abac40debcL)).seal();
  private static final ConceptSwitchIndex conceptIndex2 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xf4edb82064c444beL, 0x93d796440bb7833cL, 0x393d35efb0d2d20aL)).seal();
}
