package InterfaceCreator.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Action = 0;
  public static final int ActionEnum = 1;
  public static final int ActionReference = 2;
  public static final int Calculator = 3;
  public static final int Input = 4;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xf4edb82064c444beL, 0x93d796440bb7833cL);
    builder.put(0x4876abac40debcL, Action);
    builder.put(0x393d35efb0d226f9L, ActionEnum);
    builder.put(0x393d35efb0d2d20aL, ActionReference);
    builder.put(0x4876abac3d2f70L, Calculator);
    builder.put(0x4876abac40debbL, Input);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
